[package]
name = "krabby"
version = "0.1.4"
authors = ["Yann Jorelle <yannjorelle@protonmail.com>"]
description = "Print pokemon sprites in your terminal"
repository = "https://github.com/yannjor/krabby"
homepage = "https://github.com/yannjor/krabby"
edition = "2021"
readme = "README.md"
license = "GPL-3.0"
keywords = ["pokemon", "terminal", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli
clap = { version = "3.1.8", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
rand = "0.8.5"
rust-embed = "6.4.0"
thiserror = "1.0.30"
# Config
dirs = "4.0.0"
toml = "0.5.8"
